name: tweeter
description: A Flutter application for sharing tweets.
publish_to: 'none' 

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true