// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy0IaWP69ENajA3HcwbYByBeUT6T4XsBw',
    appId: '1:897967595665:web:4e7715171cd03cc20f5f30',
    messagingSenderId: '897967595665',
    projectId: 'mobile-app-development-d1e64',
    authDomain: 'mobile-app-development-d1e64.firebaseapp.com',
    storageBucket: 'mobile-app-development-d1e64.firebasestorage.app',
    measurementId: 'G-WZ04RG15XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWJSKdc9Hlhfmg5if8COvcKp7exTqCkOY',
    appId: '1:897967595665:android:80cc7b5bc997f6a00f5f30',
    messagingSenderId: '897967595665',
    projectId: 'mobile-app-development-d1e64',
    storageBucket: 'mobile-app-development-d1e64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5U2jgR90F2IYovFcPw0dO0WHi5DYThbg',
    appId: '1:897967595665:ios:9ad6699f7537bb900f5f30',
    messagingSenderId: '897967595665',
    projectId: 'mobile-app-development-d1e64',
    storageBucket: 'mobile-app-development-d1e64.firebasestorage.app',
    iosBundleId: 'com.example.tweeter',
  );
}
